---
- name: Drush | Check if Drush is installed (ignore if fails)
  raw: drush --version
  register: drush_installed
  ignore_errors: true

- name: Drush | install drush via composer
  command: composer global require drush/drush
  when: drush_installed.stdout.find('command not found') != -1

- name: Drush | set drush to executable
  command: chmod u+x drush chdir=/home/{{ username }}/.config/composer/vendor/drush/drush
  when: drush_installed.stdout.find('command not found') != -1

- name: Drush | link up the drush command so everyone can run it
  file: src=/home/{{ username }}/.config/composer/vendor/drush/drush/drush dest=/usr/bin/drush state=link
  when: drush_installed.stdout.find('command not found') != -1
  become: true

- name: Drush | clear drush cache
  command: drush cc drush
