---
- name: Test | NPM is installed
  shell: npm -v
  register: npm_installed
  ignore_errors: true

- name: NodeJS | Download the nvm (node version manager) install script
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh dest=/tmp/install.sh

- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - npm
    - git
    - curl
    - build-essential
    - libssl-dev
  become: yes

- name: NodeJS | Execute the nvm install script
  shell: bash install.sh chdir=/tmp executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- name: NodeJS | Register the NVM_DIR
  shell: echo $NVM_DIR
  register: nvm_dir

- name: Install the specified node version using the nvm command and set it as default
  shell: . {{ home_dir }}/.nvm/nvm.sh && nvm install 7.4.0 && nvm run 7.4.0 --version && nvm alias default 7.4.0
      creates={{ home_dir }}/.nvm/versions/node/v7.4.0
  become: yes
  become_user: "{{ username }}"


- name: Node | Check if Nodejs is installed (ignore if fails)
  raw: nodejs --version
  register: nodejs_installed
  ignore_errors: true

- name: Node | Create link to nodejs.
  shell: ln -s {{ home_dir }}/.nvm/versions/node/v7.4.0/bin/node /usr/bin/nodejs
  become: yes
  when: nodejs_installed.stdout.find('currently not installed') != -1

#- name: NodeJS | Install Grunt, Bower and Gulp
#  command: "npm install {{ item }}"
#  become: yes
#  become_user: "{{ username }}"
#  with_items:
#    - grunt
#    - grunt-cli
#    - bower
#    - gulp
#    - gulp-bower
#    - require-dir
#    - gulp-sass
