---
- hosts: all

  vars_files:
    - ../settings.yml

  roles:
    - base
    - nginx
    - php
    - mysql
    - front

  post_tasks:
    - include: tests/main.yml

  handlers:
      - include: common/handlers/main.yml
